version: 0.2


env:
  variables:
    TEST_VARIABLE: "pipa_pacii"
  parameter-store:
    FAKE_PASSWORD: "/project1/service1/dev/fakepass"

phases:
  pre_build:
    commands:
      - echo Get variables file from S3 bucket ...
      - aws s3 cp s3://codebuild-eu-west-1-8fpki2w21qua8v8y/8fpki2w21qua8v8y.txt .env
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - REPOSITORY_URI=409092538980.dkr.ecr.eu-west-1.amazonaws.com/testnodeapp/node8
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"testnodeapp-fe","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
